# NYU/NSA submission file
[main]
# minimum rp separation
rpmin = 0.1
# maximum rp separation
rpmax = 25
# number of rp bins
nrpbins = 12
# maximum integration distance along line of sight
pimax = 60
# number of mocks at a given posterior point
Nmocks = 50
# size of the simulation box
boxsize = 400
# subvolume length for jackknifing
subside = 25
# number of jackknife centres
Njack = 300
# how many times more randoms than data
Nmult = 35
# survey fractional bins
fraction_bins = [0.0, 0.015, 0.15, 0.45, 0.9]

[sampling]
parameters = ['alpha', 'scatter']
proxy = 'mvir_proxy'
max_scatter = 1.0

survey = '/mnt/zfsusers/rstiskalek/pysham/results/{}/ObsCF_{}_bin{}.p'
nd_gal = '/mnt/zfsusers/rstiskalek/pysham/results/{}/{}.npy'
halos = '/mnt/zfsusers/rstiskalek/pysham/data/halos_{}.npy'

[sampling.bounds]
alpha = [0.0, 2.0]
scatter = [0.005, 1.0]

[sampling.nside]
alpha = 30
scatter = 30

