[main]
# projected correlation function settings 
rpmin = 0.1
rpmax = 25
nrpbins = 12
pimax = 60
# number of centers for jackknifing observaitions
ncent = 300

# abundance matching setup
Nmocks = 50
boxsize = 400
subside = 25

# sampling setup

adapt_dur = 800
npoints = 1200
initial = 0
bins = 45

halos = '../BAM/hlist_1.00000.npy'
Njobs = 10
proxy = 'vvir'

[NYUmatch]
name = 'NYUmatch'
pars = ['alpha', 'scatter']
    [NYUmatch.LF]
        nd_gal = '../Data/NYUmatch/LF_NYU.npy'
        [NYUmatch.LF.0]
            scope = [-30.0, -22.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 50
        [NYUmatch.LF.1]
            scope = [-30.0, -21.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 30
        [NYUmatch.LF.2]
            scope = [-30.0, -20.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20
        [NYUmatch.LF.3]
            scope = [-30.0, -19.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 10
        [NYUmatch.LF.4]
            scope = [-22.0, -21.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 25
        [NYUmatch.LF.5]
            scope = [-21.0, -20.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 25
        [NYUmatch.LF.6]
            scope = [-20.0, -19.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20
    [NYUmatch.MF]
        nd_gal = '../Data/NYUmatch/MF_NYU.npy'
        [NYUmatch.MF.0]
            scope = [9.2, 9.8]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20
        [NYUmatch.MF.1]
            scope = [9.8, 10.4]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20
        [NYUmatch.MF.2]
            scope = [10.4, 11.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20
        [NYUmatch.MF.3]
            scope = [11.0, 15.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 50
        [NYUmatch.MF.4]
            scope = [9.2, 15.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 10
        [NYUmatch.MF.5]
            scope = [9.8, 15.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 15
        [NYUmatch.MF.6]
            scope = [10.4, 15.0]
            alpha = [0.0, 1.0]
            scatter = [0.005, 0.3]
            Nmult = 20


