[Main]
boxsize = 400
Nmocks = 50
seed = 42
CF_path = "../results/NSA_ELPETRO/"
halos_path = "../data/hlist_mvir_mpeak.npy"
attr = "ELPETRO_LOG_MASS"


[AbundanceMatch]
proxy = 'mvir_proxy'
MFpath = '../data/surveys/SMF_NSA_ELPETRO_Z015_h07.npy'
ext_range = [9.4, 14.0]


[Correlator]
subside = 25
Nmult = 30

[Bounds]
alpha = [0.0, 2.0]
scatter = [0.005, 0.35]
