[Main]
path = "../data/surveys/nsa_v1_with_zmax.fits"
randoms_path = "../data/randoms/NSA_randoms.npy"
out_folder = "../results/NSA_SERSIC/"
Nmult = 40



#=============================================================================#
[Conditions]

[Conditions.finite_condition_x_0]
attr = 'SERSIC_ABSMAG'

[Conditions.is_equal_condition]
attr = 'IN_DR7_LSS'
value = true

[Conditions.range_condition_x_1]
attr = 'SERSIC_APPMAG'
ext_range = [-1000.0, 17.6]

[Conditions.range_condition_x_2]
attr = 'ZDIST'
ext_range = [0.01, 0.15]

# These cuts are assumed to be in h=1 (the data cosmology)
# Hence looks different than the paper

# Use _SUB_ delimiter to denote different subsamples
[Conditions.range_condition_SUB_N1]
attr = 'SERSIC_ABSMAG'
ext_range = [-30.0, -22.828]

[Conditions.range_condition_SUB_N2]
attr = 'SERSIC_ABSMAG'
ext_range = [-22.828, -21.523]

[Conditions.range_condition_SUB_N3]
attr = 'SERSIC_ABSMAG'
ext_range = [-21.523, -20.860]

[Conditions.range_condition_SUB_N4]
attr = 'SERSIC_ABSMAG'
ext_range = [-20.860, -19.626]

[Conditions.range_condition_SUB_K1]
attr = 'SERSIC_LOG_MASS'
ext_range = [11.25, 15.0]

[Conditions.range_condition_SUB_K2]
attr = 'SERSIC_LOG_MASS'
ext_range = [10.721, 11.25]

[Conditions.range_condition_SUB_K3]
attr = 'SERSIC_LOG_MASS'
ext_range = [10.42, 10.721]

[Conditions.range_condition_SUB_K4]
attr = 'SERSIC_LOG_MASS'
ext_range = [9.824, 10.42]

#=============================================================================#
[Routines]

[Routines.SERSIC_LOG_MASS]
kind = 'log_routine'
attr = 'SERSIC_MASS'

[Routines.SERSIC_APPMAG]
kind = 'apparent_magnitude_routine'
redshift = 'ZDIST'
absmag = 'SERSIC_ABSMAG'
Kcorr = 'SERSIC_KCORRECT'

[Routines.SERSIC_APPMAG.cosmo]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Routines.COMOVING_DIST]
kind = 'comoving_distance_routine'
redshift = 'ZDIST'

[Routines.COMOVING_DIST.cosmo]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295


#=============================================================================#
[Indices]

[Indices.SERSIC_ABSMAG]
column = 4

[Indices.SERSIC_KCORRECT]
column = 4

#=============================================================================#
[Little_h]

[Little_h.luminosity_log_mass_little_h]
attr = 'SERSIC_LOG_MASS'

[Little_h.luminosity_log_mass_little_h.cosmo_data]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Little_h.luminosity_log_mass_little_h.cosmo_out]
kind = 'FlatLambdaCDM'
H0 = 68.8
Om0 = 0.295



[Little_h.absolute_magnitude_little_h]
attr = 'SERSIC_ABSMAG'

[Little_h.absolute_magnitude_little_h.cosmo_data]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Little_h.absolute_magnitude_little_h.cosmo_out]
kind = 'FlatLambdaCDM'
H0 = 68.8
Om0 = 0.295

#=============================================================================#
[Correlator]
rpmin = 0.1
rpmax = 25
nrpbins = 12
pimax = 60
Njack = 256
