[Main]
path = "../data/surveys/nsa_v1_with_zmax.fits"
randoms_path = "../data/randoms/NSA_randoms.npy"
out_folder = "../results/NSA_ELPETRO/"
Nmult = 40



#=============================================================================#
[Conditions]

[Conditions.finite_condition_x_0]
attr = 'ELPETRO_ABSMAG'

[Conditions.is_equal_condition]
attr = 'IN_DR7_LSS'
value = true

[Conditions.range_condition_x_1]
attr = 'ELPETRO_APPMAG'
ext_range = [-1000.0, 17.6]

[Conditions.range_condition_x_2]
attr = 'ZDIST'
ext_range = [0.01, 0.15]

# These cuts are assumed to be in h=1 (the data cosmology)
# Hence looks different than the paper

# Use _SUB_ delimiter to denote different subsamples
[Conditions.range_condition_SUB_N1]
attr = 'ELPETRO_ABSMAG'
ext_range = [-30.0, -22.315]

[Conditions.range_condition_SUB_N2]
attr = 'ELPETRO_ABSMAG'
ext_range = [-22.315, -21.33]

[Conditions.range_condition_SUB_N3]
attr = 'ELPETRO_ABSMAG'
ext_range = [-21.33, -20.74]

[Conditions.range_condition_SUB_N4]
attr = 'ELPETRO_ABSMAG'
ext_range = [-20.74, -19.54]

[Conditions.range_condition_SUB_K1]
attr = 'ELPETRO_LOG_MASS'
ext_range = [11.07, 15.0]

[Conditions.range_condition_SUB_K2]
attr = 'ELPETRO_LOG_MASS'
ext_range = [10.64, 11.07]

[Conditions.range_condition_SUB_K3]
attr = 'ELPETRO_LOG_MASS'
ext_range = [10.36, 10.64]

[Conditions.range_condition_SUB_K4]
attr = 'ELPETRO_LOG_MASS'
ext_range = [9.79, 10.3]

#=============================================================================#
[Routines]

[Routines.ELPETRO_LOG_MASS]
kind = 'log_routine'
attr = 'ELPETRO_MASS'

[Routines.ELPETRO_APPMAG]
kind = 'apparent_magnitude_routine'
redshift = 'ZDIST'
absmag = 'ELPETRO_ABSMAG'
Kcorr = 'ELPETRO_KCORRECT'

[Routines.ELPETRO_APPMAG.cosmo]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Routines.COMOVING_DIST]
kind = 'comoving_distance_routine'
redshift = 'ZDIST'

[Routines.COMOVING_DIST.cosmo]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295


#=============================================================================#
[Indices]

[Indices.ELPETRO_ABSMAG]
column = 4

[Indices.ELPETRO_KCORRECT]
column = 4

#=============================================================================#
[Little_h]

[Little_h.luminosity_log_mass_little_h]
attr = 'ELPETRO_LOG_MASS'

[Little_h.luminosity_log_mass_little_h.cosmo_data]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Little_h.luminosity_log_mass_little_h.cosmo_out]
kind = 'FlatLambdaCDM'
H0 = 68.8
Om0 = 0.295



[Little_h.absolute_magnitude_little_h]
attr = 'ELPETRO_ABSMAG'

[Little_h.absolute_magnitude_little_h.cosmo_data]
kind = 'FlatLambdaCDM'
H0 = 100
Om0 = 0.295

[Little_h.absolute_magnitude_little_h.cosmo_out]
kind = 'FlatLambdaCDM'
H0 = 68.8
Om0 = 0.295

#=============================================================================#
[Correlator]
rpmin = 0.1
rpmax = 25
nrpbins = 12
pimax = 60
Njack = 256
