[Main]
boxsize = 400
Nmocks = 50
seed = 42
CF_path = "../results/NYU/"
halos_path = "../data/hlist_mvir_mpeak.npy"
attr = "ABSMAG"


[AbundanceMatch]
proxy = 'mvir_proxy'
LFpath = '../data/surveys/LF_NYU_Z015_h07.npy'
ext_range = [-27.0, -16.0]


[Correlator]
subside = 25
Nmult = 30

[Bounds]
alpha = [0.9, 2.0]
scatter = [0.005, 0.85]
